BookStore-Lab/
│
├── README.md
├── LICENSE
├── Architecture.png
├── Data_Model.png
│
├── 01_Setup
│   ├── 01 - Create Structures and Tables
│   ├── 02 - Load Books
│   ├── 03 - Load Customers
│   ├── 04 - Load Orders
│   └── 05 - Load Orders Updates
│
├── 02_SQL
│   ├── 06 - Create User Defined Functions
│   ├── 07 - Create Views
│   ├── 08 - Validation Queries
│   ├── 09 - Merge Into
│   ├── 10 - Window Functions
│   └── 11 - Higher Order Functions
│
├── 03_Streaming
│   ├── 12 - Streaming
│   └── 13 - Cleanup
│